language: csharp
solution: CodeChecker.sln
install:
  - nuget restore CodeChecker.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
script:
  - xbuild /p:TargetFrameworkVersion="v4.5"
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./CodeChecker.Tests/bin/Debug/CodeChecker.Tests.dll

